### ISSUE TITLE
Watch for new namespace to copy certificate into

### ISSUE THREAD

**Issue by vitorarins** [estafette/estafette-letsencrypt-certificate#32] opened 2020-03-17 14:11 UTC
When the new secret is created with option to copy to all namespaces the certificate secret is successfully copied.

But after the certificate is there, if new namespaces are created, the secret is not copied to this new namespace.

**Comment by JorritSalverda** [comment] 2020-06-12 08:48
To implement this the following needs to happen:

- add `watch` verb to resource `namespaces` in the clusterrole
- watch namespaces in code and act on `eventType == k8s.EventAdded`
- in that case look for all secrets with the `estafette.io/letsencrypt-certificate-copy-to-all-namespaces` annotation and copy those into the new namespace
- if this leads to performance problems because too many secrets are loaded at once you can look at chuncking results, see https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks

In order to create a release

- link the issue to a milestone with the next patch version after the previous release
- assign the issue to yourself to get mentioned in the release notes
- make sure semver and release branch in the `.estafette.yaml` match the milestone version
- once the issue is resolved and merged into master create a release branch with the milestone version, push it, build it
- trigger the `release` release once the release branch has been built succesfully; this will create a github release with release notes

**Closed** 2020-06-26 09:38 UTC
